### ISSUE TITLE
422 in newrelic:notify-deployment

### ISSUE THREAD

**Issue by wackymole** [ekino/EkinoNewRelicBundle#117]
I can't seem to get around an HTTP 422 (Unprocessable Entity) when running the `notify-deployment` command.

* config
```yaml
ekino_new_relic:
    enabled: "%newrelic_reporting_enabled%"
    application_name: "%newrelic_application_name%"
    api_key: "%newrelic_api_key%"
    license_key: "%newrelic_license_key%"
    xmit: false
    logging: false
    instrument: false
    log_exceptions: true
    log_commands: true
    using_symfony_cache: true
    transaction_naming: route
    transaction_naming_service: ~
    ignored_routes: []
    ignored_paths: []
    ignored_commands: []
```
All of the parameters are defined in parameters.yml correctly.

* `bin/console about`
```
-------------------- ---------------------------------------------- 
  Symfony                                                            
 -------------------- ---------------------------------------------- 
  Version              3.3.5                                         
  End of maintenance   01/2018                                       
  End of life          07/2018                                       
 -------------------- ---------------------------------------------- 
  Kernel                                                             
 -------------------- ---------------------------------------------- 
  Type                 AppKernel                                     
  Name                 app                                           
  Environment          dev                                           
  Debug                true                                          
  Charset              UTF-8                                         
  Root directory       ./app                                         
  Cache directory      ./var/cache/dev (970 KiB)                     
  Log directory        ./var/logs (28.0 MiB)                         
 -------------------- ---------------------------------------------- 
  PHP                                                                
 -------------------- ---------------------------------------------- 
  Version              7.1.8-2+ubuntu16.04.1+deb.sury.org+4          
  Architecture         64 bits                                       
  Intl locale          en_US                                         
  Timezone             America/New_York (2017-08-22T13:16:19-04:00)  
  OPcache              true                                          
  APCu                 false                                         
  Xdebug               true                                          
 -------------------- ----------------------------------------------
```

* terminal output
```
$ php bin/console newrelic:notify-deployment
Deployment not recorded to 'dev_myapp': Received HTTP status 422
13:37:24 ERROR     [console] Command "newrelic:notify-deployment" exited with code "3" ["command" => "newrelic:notify-deployment","code" => 3] []
```

Any suggestions on how to further troubleshoot or resolve this?
