### ISSUE TITLE
Using `extension_loaded` when building the container is not the right approach

### ISSUE THREAD

**Issue by sroze** [ekino/EkinoNewRelicBundle#182]
I've spent a bit of time debugging why the bundle wouldn't work with our Heroku-based setup. It turns out that it's because it's using the `extension_loaded('newrelic')` condition when building the cache to know to use either the "blackhole" or the "real" implementation. 

The reason this happened? The container is built during the Heroku build phase. Because the extension is only enabled after, this `extension_loaded` end up being false and it silently uses the blackhole configuration.

## Next steps?

1. The Blackhole should log a warning (at least debug) when doing so, because there is no way to know that it used the blackhole one (`logging: true` still logs that it "does the job" because it's a decorator).
2. Uses `extension_loaded` within an implementation of `NewRelicInteractorInterface` that could be called `TolerateNoPhpExtensionInterfactor` that would either route to the blackhole or the "real" one.

WDYT?

**Comment by Nyholm** [comment]
Hm.. We have taken a slightly different route in version 2 (now beta). See https://github.com/ekino/EkinoNewRelicBundle/blob/master/DependencyInjection/EkinoNewRelicExtension.php#L142-L154

We have modes for "auto" (buildtime), "enabled", "disabled" and "adaptive" (runtime).

**Comment by sroze** [comment]
What's the point of `auto` if you have `adaptive`? :)

**Comment by Nyholm** [comment]
One is for build time and one is for run time. From what I understood, platforms (like Heroku) supports to enabling/disabling PHP extension on the fly. So you need to check for the extension every time you want to use a NewRelic function. (adaptive)

"Auto" is where we only check on build time. If you deploy on a "normal" VPS you might want to enable NewRelic if the extension is available. My personal use case is that I do not have NewRelic installed on Staging but only in Production.

**Comment by Nyholm** [comment]
Hm. 
`adaptive` will always work and more people like you will not get into this situation. This is awesome. 
However, `auto` has a better performance.... But it is just negligible.

Im 👍 for making `adaptive` the default. But we should be clear in the docs how to change and what they really are.

**Comment by jderusse** [comment]
:+1: for switching to `adaptive` when `interactor` is not set. And using `ekino.new_relic.interactor.auto` in README.md documentation (with a notification about requirements in build time)

**Comment by Nyholm** [comment]
FYI, Just added #189 as a fix for this issue.

**Comment by pesseyjulien** [comment]
Hi @sroze,

Sorry to unearth such an old issue but did you managed to make this bundle works using the Heroku Newrelic add-on ?

Here is my config :

```
ekino_new_relic:
    enabled: true
    logging: true
    application_name: "%env(NEW_RELIC_APP_NAME)%"
    api_key: "%env(NEWRELIC_API_KEY)%"
    interactor: auto
    exceptions: true
    deprecations: false
    instrument: true
    http:
        enabled: true
        using_symfony_cache: true
    monolog:
        enabled: true
        channels: [ app ]
        level: info
    commands:
        enabled: true
        ignored_commands: [ ]
```

What env variables did you leave ?

Thanks in advance for your help,
Julien
