### ISSUE TITLE
Command line app is not tracked

### ISSUE THREAD

**Issue by Kolesar** [ekino/EkinoNewRelicBundle#211]
My configuration is like:

```
ekino_new_relic:
    enabled: true
    application_name:  "Service Name"
    deployment_names: ~
    api_key: "%env(NEWRELIC_API_KEY)%"
    logging: true
    interactor: ~ 
    twig: false
    exceptions: true
    deprecations: true
    http:
        enabled: false
    monolog:
        enabled: true
        channels: [app]
        level: error
    commands:
        enabled: true
        ignored_commands: []
```

In the New Relic dashboard I see this "Service Name" name in the Application list, but, all transaction are tracked under default name from the newrelic.ini file.

My application is the console one and unfortunately, I see there only main command: `bin/console` nothing deeper which command exactly is run, because `bin/console` has arguments, of course, and it is multiprocessing application.

I'm new with New Relic and do not know how it works in details. Any help or hint here is welcome.
