### ISSUE TITLE
Enabling extension and monolog leads to unexpected errors when no extension

### ISSUE THREAD

**Issue by PWalkow** [ekino/EkinoNewRelicBundle#242]
As in #221 , enabling both monolog and extension leads to `MissingExtensionException` on a LoggerInterface call.

Minimum configuration:
```
### ekino_new_relic.yaml
ekino_new_relic:
    enabled: true
    exceptions: true
    deprecations: true
    monolog:
        enabled: true
        level: error
```

should there be an extra check before loading the monolog handler even if it is not supported by missing extension to avoid playing with the configuration for environments that does not have an extension?
