### ISSUE TITLE
Passing a boolean as the first argument to "Symfony\Component\PropertyAccess\PropertyAccessor::__construct()" is deprecated

### ISSUE THREAD

**Issue by classifieds-maciej** [ekino/EkinoNewRelicBundle#255]
I'm having this kind of deprecation notice:

`Noticed exception 'Ekino\NewRelicBundle\Exception\DeprecationException' with message 'Since symfony/property-access 5.2: Passing a boolean as the first argument to "Symfony\Component\PropertyAccess\PropertyAccessor::__construct()" is deprecated. Pass a combination of bitwise flags instead (i.e an integer).' in /app/vendor/symfony/deprecation-contracts/function.php:25`

My config is similar to documentation:
```
ekino_new_relic:
    enabled: true
    xmit: true
    application_name: '%env(APPLICATION)%'
    api_key: '%env(KEY)%'
    license_key: '%env(LICENSE)%'
```

I'm not sure where does this notice come from, can you help?
