### ISSUE TITLE
Not working on Heroku ?

### ISSUE THREAD

**Issue by pesseyjulien** [ekino/EkinoNewRelicBundle#273]
Hi,

Is there any way to make sure the integration is working ?

Because I have installed the bundle and the Newrelic add-on on Heroku but I don't see my background jobs on New relic.

Here is my config :

```
ekino_new_relic:
    enabled: true
    application_name: "%env(NEW_RELIC_APP_NAME)%"
    api_key: "%env(NEWRELIC_API_KEY)%"
    interactor: auto
    exceptions: false
    deprecations: false
    instrument: false
    commands:
        enabled: true
```

I alos have a newrelic.ini :
[newrelic]
newrelic.enabled=true
newrelic.browser_monitoring.auto_instrument = false
newrelic.transaction_tracer.enabled = true
newrelic.transaction_tracer.threshold = "500ms"

Maybe the API KEY is not good, how can I tell what is wrong ?

Thanks in advance,
Julien
