### ISSUE TITLE
Monolog logs not making it to New Relic

### ISSUE THREAD

**Issue by jag-ermeister** [ekino/EkinoNewRelicBundle#282]
I'm extremely confident that this is user error and that I have not configured things correctly.  I have the PHP Agent and daemon installed in the docker image that is running my Symfony application.  My new relic configuration looks as follows:

```
ekino_new_relic:
    enabled: true
    application_name: 'Application name'
    api_key: "%env(NEWRELIC_API_KEY)%"
    exceptions: true
    deprecations: true
    logging: true
    instrument: true
    monolog:
        enabled: true
        channels: ~

```

I have a lot of metrics making it into New Relic, but none of the logs.  Any ideas as to why?  Do I also need to configure a `newrelic` handler in my `monolog` configuration? Something like this?

```
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: php://stderr
            level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        newrelic: #this here?
            type: stream
            level: info

```

Or is that unnecessary with the `monolog` configuration in the `ekino_new_relic` settings?  I've tried both ways with no positive results.  Any thoughts?

**Comment by jag-ermeister** [comment]
I ended up installing the newrelic/monolog-enricher next to this bundle and am using the latter for logs, which works great.  I'm still not 100% sure why that works.  I'm closing this issue, though, as I'm sure this is still due to some misconfiguration on my part.

**Comment by nuryagdym** [comment]
I also faced the same issue and did some debugging.
To enable monolog logging you can add following configs.
```yaml
ekino_new_relic:
    monolog:
        enabled: true
        channels: ~
```
This config will send any logs with level **error** or higher to NewRelic. And logs will be in `Errors` section in NewRelic.
The problem is you can't define `level` range for this logging. But, even if you could it will not be good, because it will still be under `Errors` section in NewRelic, because monolog's [NewRelicHandler](https://github.com/Seldaek/monolog/blob/main/src/Monolog/Handler/NewRelicHandler.php#L60) pushes them as errors.

As @jag-ermeister suggested I also used `newrelic/monolog-enricher` which send logs using `curl`: https://github.com/newrelic/newrelic-monolog-logenricher-php/blob/master/src/AbstractHandler.php#L124
I configured it in following way:
```yaml
services:
  newrelic_buffered: # send logs in batch
    class: Monolog\Handler\BufferHandler
    arguments:
      $handler: '@NewRelic\Monolog\Enricher\Handler'

monolog:
  channels:
    - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
  handlers:
    newrelic_log_filter:
      type: fingers_crossed
      action_level: error # when any error log is encountered, logs of all level will be pushed to the NewRelic
      handler: newrelic
      excluded_http_codes: [404, 405]
      channels: [ "!event", "!deprecation" ]
    newrelic:
      type: service
      id: newrelic_buffered
     # setting level here will not work, if you need to specify you need to configure @NewRelic\Monolog\Enricher\Handler
```

I did not configure anything else such as license key, api key because `NewRelic\Monolog\Enricher\AbstractHandler` automatically configures itself in its constructor.
Logs from `newrelic/monolog-enricher` goes into **Logs** section in NewRelic. 
You can also find documentation [here](https://docs.newrelic.com/docs/logs/forward-logs/enable-log-management-new-relic/).

If logging with monolog does not meet your requirementa you can check this [docs](https://docs.newrelic.com/docs/logs/forward-logs/enable-log-management-new-relic/) for other ways of pushing it to NewRelic
