### ISSUE TITLE
Transaction/Browser metrics stopped reporting after deploying the bundle

### ISSUE THREAD

**Issue by tristanbes** [ekino/EkinoNewRelicBundle#57]
Hi,

Transaction/Browser metrics has stopped when I've deployed this bundle.
![capture](https://cloud.githubusercontent.com/assets/346010/2671598/9892e1a2-c0dc-11e3-9e1f-5a7a4f453dde.PNG)

Here's my configuration :

```yml
ekino_new_relic:
    application_name: myappname
    api_key: ...
    license_key: ...
    xmit: false                           
    logging: false                       
    instrument: false                    
    log_exceptions: true                 
    log_commands: true                   
    using_symfony_cache: true           
    transaction_naming: route          
```

We do use Symfony AppCache for our front end.

**The application name is set both in php.ini and in the bundle configuration** (so it maybe related to this issue #24).

But if I don't need to set the name of the application in the bundle configuration to prevent data loss, isn't that conflicting with the documentation :
`Symfony http cache: If true is required to set the application_name.`

ping @magnusnordlander @rande @fabian
