### ISSUE TITLE
Some requests are not caught by the bundle

### ISSUE THREAD

**Issue by Nyholm** [ekino/EkinoNewRelicBundle#87]
I run my Symfony application behind a reverse proxy server (Varnish). I use both ESI and hinclude. I got two New Relic license keys one for my Wordpress application (AAA) which I defined in php.ini and one for the Symfony applicaiton (BBB) which I defined in the bundle config. 

When I look at the AAA account in New Relic I find lots of Symfony requests. Both main requests and ESI requests. Both cachable requests and non-cachable requests. 

I can't figure out why the `RequestListener::onCoreRequest` isn't called or why it is not setting the application and transaction name as it should .

My config looks as follows: 
``` yml
#new relic
ekino_new_relic:
    application_name: %new_relic_name%
    enabled: %new_relic_enabled%
    transaction_naming: service
    instrument: true
    transaction_naming_service: new_relic.transaction_naming_strategy
    api_key: %api_key%
    log_exceptions: true
```
I'm using version 1.2.2.
